name: Continous delivery on Anaconda Cloud (build in docker container)
on:

  push:

    tags:
      - v*

jobs:

  build_and_publish:

    runs-on: ubuntu-latest

    container: prairielearn/centos7-python

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: DEBUG
        run: |
          pwd
          ls -la
          echo "GITHUB_REF=$GITHUB_REF"

      - name: Installing Anaconda
        run: |
          echo "Install anaconda 5.3.0 x86_64"
          wget -q https://repo.anaconda.com/archive/Anaconda3-5.3.0-Linux-x86_64.sh
          echo "cfbf5fe70dd1b797ec677e63c61f8efc92dad930fd1c94d60390bb07fdc09959  Anaconda3-5.3.0-Linux-x86_64.sh" > anaconda_hash_sha256
          sha256sum -c anaconda_hash_sha256
          bash Anaconda3-5.3.0-Linux-x86_64.sh -b -p /opt/anaconda3
          ln -s /opt/anaconda3/etc/profile.d/conda.sh /etc/profile.d/conda.sh


      - name: Anaconda info
        run: |
          which python
          /opt/anaconda3/bin/conda --version

      - name: Installing conda-build
        run: |
          /opt/anaconda3/bin/conda install conda-build
          /opt/anaconda3/bin/conda update conda-build

      - name: Download Agilepy-recipe
        run: |
          git clone https://github.com/AGILESCIENCE/Agilepy-recipe.git
          cp Agilepy-recipe/github-workflow-build/activate.sh ./
          cp Agilepy-recipe/github-workflow-build/deactivate.sh ./
          cp Agilepy-recipe/github-workflow-build/build.sh ./
          cp Agilepy-recipe/github-workflow-build/meta.yaml ./

      - name: Debug
        run: |
          pwd
          ls -la
