name: Continous delivery on Anaconda Cloud
on:

  push:

    tags:
      - v*

jobs:

  build_and_publish:

    runs-on: ubuntu-18.04

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: DEBUG
        run: |
          pwd
          ls -la
          echo "GITHUB_REF=$GITHUB_REF"

      - name: Installing Anaconda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: True
          conda-channels: conda-forge, addis.inaf, LeonardoBaroncelli

      - name: Anaconda info
        run: |
          which python
          conda --version

      - name: Installing conda-build
        run: |
          conda install conda-build
          conda update conda-build

      - name: Download Agilepy-recipe
        run: |
          git clone https://github.com/AGILESCIENCE/Agilepy-recipe.git
          cp Agilepy-recipe/github-workflow-build/activate.sh ./
          cp Agilepy-recipe/github-workflow-build/deactivate.sh ./
          cp Agilepy-recipe/github-workflow-build/build.sh ./
          cp Agilepy-recipe/github-workflow-build/meta.yaml ./

      - name: Debug
        run: |
          pwd
          ls -la

      - name: Build and Publish on Anaconda cloud
        run: |
          conda config --set anaconda_upload yes
          anaconda login --username $INPUT_ANACONDAUSERNAME --password $INPUT_ANACONDAPASSWORD
          conda build .
          anaconda logout
