name: new_release
on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:

  setup:

    runs-on: ubuntu-18.04

    steps:

      - name: DEBUG
        run: |
          pwd
          ls -la
          echo "GITHUB_REF=$GITHUB_REF"

      - uses: actions/checkout@v2

      - name: DEBUG
        run: |
          pwd
          ls -la


      - uses: s-weigand/setup-conda@v1
        with:
          update-conda: True
          conda-channels: conda-forge, addis.inaf

      - name: Conda info
        run: |
          which python
          conda --version

      - name: Installing conda-build
        run: |
          conda install conda-build
          conda update conda-build

      - name: Download Agilepy-recipe
        run: git clone https://github.com/AGILESCIENCE/Agilepy-recipe.git

      - name: Debug
        run: |
          pwd
          ls -la

      - name: Conda build
        run: |
          cd Agilepy-recipe/github-workflow-build
          conda-build .
